version: '3'
services:
  web:
    image: yoavshprung/today:latest
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb

