apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  selector:
    app: my-flask-app  # Select pods with this label
  ports:
    - protocol: TCP
      port: 80  # Port to expose on the service
      targetPort: 5000  # Port on the pods where the app is listening
  type: LoadBalancer  # Expose the service externally (requires cloud provider support)
